# language: php

checks:
  php:
    verify_property_names: true
    verify_argument_usable_as_reference: true
    verify_access_scope_valid: true
    variable_existence: true
    useless_calls: true
    code_rating: true
    duplication: true

filter:
  paths:
    - src/*

tools:
  sensiolabs_security_checker: true
  external_code_coverage: false

build:
  environment:
    php: 8.0
  tests:
    override:
      - command: 'vendor/bin/phpunit --coverage-clover=code-coverage.xml'
        coverage:
          file: 'code-coverage.xml'
          format: 'php-clover'
